apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    run: mkdocs
  name: mkdocs
spec:
  replicas: 2
  selector:
    run: mkdocs
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: mkdocs
    spec:
      containers:
      - image: nishipy/mkdocs:sha-88d5354
        name: mkdocs
        resources: {}
  test: false
  triggers:
    - type: ConfigChange
